# Generated by Django 5.2.1 on 2025-05-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_remove_userprofile_name_remove_userprofile_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ppt_bg_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ppt_highlight_color',
            field=models.CharField(default='#00ff00', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ppt_text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
