# Generated by Django 5.2.1 on 2025-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0003_userprofile_ppt_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ppt_correct_choice_text',
            field=models.CharField(default='#00ff00', max_length=7),
        ),
    ]
