# Generated by Django 5.2.1 on 2025-05-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0005_alter_userprofile_ppt_correct_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ppt_bg_color',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ppt_highlight_color',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ppt_text_color',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
