# Generated by Django 5.2.1 on 2025-05-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0006_alter_userprofile_ppt_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ppt_correct_choice_text',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
